### ISSUE TITLE
Playback Error

### ISSUE THREAD

**Issue by abauer** [EnsemblePlayer/chorus#15]
!High Priority!
log:
[044a9784] gnutls tls session error: Error in the pull function.
[0438c794] main access error: read error: Connection reset by peer

Skips music halfway through

**Comment by abauer** [comment]
could be solved with tracking progress of song? #5

**Comment by abauer** [comment]
additional separate error
log:
Type=Google
Playing a song from Google
Traceback (most recent call last):
  File "PlayerExecute.py", line 186, in <module>
    main()
  File "PlayerExecute.py", line 43, in main
    response = urllib2.urlopen('http://ensembleplayer.me//api/player.php?id='+st
r(PlayerID)+'&next='+str(nextSong))
  File "C:\Python27\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 10060] A connection attempt failed becau
se the connected party did not properly respond after a period of time, or estab
lished connection failed because connected host has failed to respond>

Halfway through song
